version: "3"
services:
    # start the ganache cli container
    ganache-cli:
        container_name: ganache-cli
        build:
            context: ./ganache-cli
        # note host:container
        ports:
            - 5545:8545
    truffle-suite:
        container_name: truffle-suite
        build:
            context: ./truffle-suite
        stdin_open: true # docker run -i
        tty: true # docker run -t
